# Generated by Django 4.1.7 on 2023-04-08 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NW', '0002_alter_category_options_alter_news_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='price',
        ),
        migrations.RemoveField(
            model_name='news',
            name='quantity',
        ),
    ]
