# Generated by Django 4.1.7 on 2023-04-09 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NW', '0004_alter_news_options_news_date_pub'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['date_pub'], 'verbose_name': 'News', 'verbose_name_plural': 'News'},
        ),
    ]
