# Generated by Django 4.1.7 on 2023-04-09 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NW', '0005_alter_news_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['-date_pub'], 'verbose_name': 'News', 'verbose_name_plural': 'News'},
        ),
    ]
