# Generated by Django 4.1.7 on 2023-04-09 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NW', '0006_alter_news_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': 'News', 'verbose_name_plural': 'News'},
        ),
    ]
